[2025-03-04T12:27:26.552-0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-04T12:27:26.809-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: EtlWeather.SendMessage scheduled__2025-02-19T00:00:00+00:00 [queued]>
[2025-03-04T12:27:26.928-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: EtlWeather.SendMessage scheduled__2025-02-19T00:00:00+00:00 [queued]>
[2025-03-04T12:27:26.929-0600] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-04T12:27:27.131-0600] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): SendMessage> on 2025-02-19 00:00:00+00:00
[2025-03-04T12:27:27.144-0600] {standard_task_runner.py:72} INFO - Started process 19681 to run task
[2025-03-04T12:27:27.166-0600] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'EtlWeather', 'SendMessage', 'scheduled__2025-02-19T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/dataEngineering.py', '--cfg-path', '/tmp/tmp4txh9sxd']
[2025-03-04T12:27:27.177-0600] {standard_task_runner.py:105} INFO - Job 17: Subtask SendMessage
[2025-03-04T12:27:27.762-0600] {task_command.py:467} INFO - Running <TaskInstance: EtlWeather.SendMessage scheduled__2025-02-19T00:00:00+00:00 [running]> on host IMNOTROY.
[2025-03-04T12:27:28.503-0600] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='EtlWeather' AIRFLOW_CTX_TASK_ID='SendMessage' AIRFLOW_CTX_EXECUTION_DATE='2025-02-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-19T00:00:00+00:00'
[2025-03-04T12:27:28.508-0600] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-04T12:28:44.655-0600] {job.py:229} INFO - Heartbeat recovered after 51.99 seconds
[2025-03-04T12:29:05.389-0600] {job.py:229} INFO - Heartbeat recovered after 47.37 seconds
[2025-03-04T12:30:21.912-0600] {job.py:229} INFO - Heartbeat recovered after 16.65 seconds
[2025-03-04T12:32:12.043-0600] {job.py:229} INFO - Heartbeat recovered after 118.64 seconds
[2025-03-04T12:32:29.274-0600] {python.py:240} INFO - Done. Returned value was: Done!
[2025-03-04T12:32:30.668-0600] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-04T12:32:30.686-0600] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=EtlWeather, task_id=SendMessage, run_id=scheduled__2025-02-19T00:00:00+00:00, execution_date=20250219T000000, start_date=20250304T182726, end_date=20250304T183230
[2025-03-04T12:32:31.071-0600] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-04T12:32:31.221-0600] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-04T12:32:31.226-0600] {local_task_job_runner.py:245} INFO - ::endgroup::
