[2025-03-02T00:25:56.531-0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-02T00:25:56.577-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: EtlWeather.StoreData manual__2025-03-02T06:23:00.234806+00:00 [queued]>
[2025-03-02T00:25:56.604-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: EtlWeather.StoreData manual__2025-03-02T06:23:00.234806+00:00 [queued]>
[2025-03-02T00:25:56.605-0600] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-02T00:25:56.642-0600] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): StoreData> on 2025-03-02 06:23:00.234806+00:00
[2025-03-02T00:25:56.655-0600] {standard_task_runner.py:72} INFO - Started process 48762 to run task
[2025-03-02T00:25:56.691-0600] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'EtlWeather', 'StoreData', 'manual__2025-03-02T06:23:00.234806+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/dag_1.py', '--cfg-path', '/tmp/tmprqo0q5w1']
[2025-03-02T00:25:56.705-0600] {standard_task_runner.py:105} INFO - Job 55: Subtask StoreData
[2025-03-02T00:25:56.927-0600] {task_command.py:467} INFO - Running <TaskInstance: EtlWeather.StoreData manual__2025-03-02T06:23:00.234806+00:00 [running]> on host IMNOTROY.
[2025-03-02T00:25:57.219-0600] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='EtlWeather' AIRFLOW_CTX_TASK_ID='StoreData' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T06:23:00.234806+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-02T06:23:00.234806+00:00'
[2025-03-02T00:25:57.221-0600] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-02T00:25:57.356-0600] {__init__.py:149} INFO - package: mysql.connector.plugins
[2025-03-02T00:25:57.356-0600] {__init__.py:150} INFO - plugin_name: caching_sha2_password
[2025-03-02T00:25:57.357-0600] {__init__.py:154} INFO - AUTHENTICATION_PLUGIN_CLASS: MySQLCachingSHA2PasswordAuthPlugin
[2025-03-02T00:25:57.358-0600] {__init__.py:149} INFO - package: mysql.connector.plugins
[2025-03-02T00:25:57.359-0600] {__init__.py:150} INFO - plugin_name: mysql_native_password
[2025-03-02T00:25:57.360-0600] {__init__.py:154} INFO - AUTHENTICATION_PLUGIN_CLASS: MySQLNativePasswordAuthPlugin
[2025-03-02T00:25:57.455-0600] {dag_1.py:62} INFO - Data stored succesfully!
[2025-03-02T00:25:57.466-0600] {python.py:240} INFO - Done. Returned value was: None
[2025-03-02T00:25:57.479-0600] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-02T00:25:57.480-0600] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=EtlWeather, task_id=StoreData, run_id=manual__2025-03-02T06:23:00.234806+00:00, execution_date=20250302T062300, start_date=20250302T062556, end_date=20250302T062557
[2025-03-02T00:25:57.557-0600] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-02T00:25:57.580-0600] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-02T00:25:57.582-0600] {local_task_job_runner.py:245} INFO - ::endgroup::
