[2025-03-02T00:24:59.326-0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-02T00:25:01.507-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: EtlWeather.SendMessage manual__2025-03-02T06:23:00.234806+00:00 [queued]>
[2025-03-02T00:25:01.929-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: EtlWeather.SendMessage manual__2025-03-02T06:23:00.234806+00:00 [queued]>
[2025-03-02T00:25:01.960-0600] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-02T00:25:03.095-0600] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): SendMessage> on 2025-03-02 06:23:00.234806+00:00
[2025-03-02T00:25:03.126-0600] {standard_task_runner.py:72} INFO - Started process 48633 to run task
[2025-03-02T00:25:03.160-0600] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'EtlWeather', 'SendMessage', 'manual__2025-03-02T06:23:00.234806+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/dag_1.py', '--cfg-path', '/tmp/tmpppwl7w1z']
[2025-03-02T00:25:03.185-0600] {standard_task_runner.py:105} INFO - Job 54: Subtask SendMessage
[2025-03-02T00:25:05.853-0600] {task_command.py:467} INFO - Running <TaskInstance: EtlWeather.SendMessage manual__2025-03-02T06:23:00.234806+00:00 [running]> on host IMNOTROY.
[2025-03-02T00:25:09.008-0600] {job.py:229} INFO - Heartbeat recovered after 12.84 seconds
[2025-03-02T00:25:22.758-0600] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='EtlWeather' AIRFLOW_CTX_TASK_ID='SendMessage' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T06:23:00.234806+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-02T06:23:00.234806+00:00'
[2025-03-02T00:25:23.009-0600] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-02T00:25:27.137-0600] {job.py:229} INFO - Heartbeat recovered after 18.27 seconds
[2025-03-02T00:25:49.945-0600] {job.py:229} INFO - Heartbeat recovered after 24.86 seconds
[2025-03-02T00:25:49.972-0600] {python.py:240} INFO - Done. Returned value was: Done!
[2025-03-02T00:25:50.255-0600] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-02T00:25:50.256-0600] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=EtlWeather, task_id=SendMessage, run_id=manual__2025-03-02T06:23:00.234806+00:00, execution_date=20250302T062300, start_date=20250302T062501, end_date=20250302T062550
[2025-03-02T00:25:50.438-0600] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-02T00:25:50.458-0600] {local_task_job_runner.py:245} INFO - ::endgroup::
