[2025-02-27T13:05:03.743-0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-27T13:05:04.297-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: EtlWeather.SendMessage scheduled__2025-02-21T00:00:00+00:00 [queued]>
[2025-02-27T13:05:04.356-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: EtlWeather.SendMessage scheduled__2025-02-21T00:00:00+00:00 [queued]>
[2025-02-27T13:05:04.358-0600] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-27T13:05:04.733-0600] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): SendMessage> on 2025-02-21 00:00:00+00:00
[2025-02-27T13:05:04.885-0600] {standard_task_runner.py:72} INFO - Started process 43594 to run task
[2025-02-27T13:05:05.143-0600] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'EtlWeather', 'SendMessage', 'scheduled__2025-02-21T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/dag_1.py', '--cfg-path', '/tmp/tmp449ygt4z']
[2025-02-27T13:05:05.205-0600] {standard_task_runner.py:105} INFO - Job 6: Subtask SendMessage
[2025-02-27T13:05:07.697-0600] {task_command.py:467} INFO - Running <TaskInstance: EtlWeather.SendMessage scheduled__2025-02-21T00:00:00+00:00 [running]> on host IMNOTROY.
[2025-02-27T13:06:51.631-0600] {job.py:229} INFO - Heartbeat recovered after 110.91 seconds
[2025-02-27T13:07:17.854-0600] {job.py:229} INFO - Heartbeat recovered after 27.38 seconds
[2025-02-27T13:07:18.519-0600] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='EtlWeather' AIRFLOW_CTX_TASK_ID='SendMessage' AIRFLOW_CTX_EXECUTION_DATE='2025-02-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-21T00:00:00+00:00'
[2025-02-27T13:07:18.530-0600] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-27T13:07:23.170-0600] {job.py:229} INFO - Heartbeat recovered after 22.66 seconds
[2025-02-27T13:12:18.898-0600] {python.py:240} INFO - Done. Returned value was: Done!
[2025-02-27T13:12:19.919-0600] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-27T13:12:19.938-0600] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=EtlWeather, task_id=SendMessage, run_id=scheduled__2025-02-21T00:00:00+00:00, execution_date=20250221T000000, start_date=20250227T190504, end_date=20250227T191219
[2025-02-27T13:12:20.306-0600] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-27T13:12:20.449-0600] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-27T13:12:20.452-0600] {local_task_job_runner.py:245} INFO - ::endgroup::
