[2025-03-04T12:27:32.504-0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-04T12:27:32.536-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: EtlWeather.SendMessage scheduled__2025-03-01T00:00:00+00:00 [queued]>
[2025-03-04T12:27:32.558-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: EtlWeather.SendMessage scheduled__2025-03-01T00:00:00+00:00 [queued]>
[2025-03-04T12:27:32.559-0600] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-04T12:27:32.627-0600] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): SendMessage> on 2025-03-01 00:00:00+00:00
[2025-03-04T12:27:32.638-0600] {standard_task_runner.py:72} INFO - Started process 19766 to run task
[2025-03-04T12:27:32.654-0600] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'EtlWeather', 'SendMessage', 'scheduled__2025-03-01T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/dataEngineering.py', '--cfg-path', '/tmp/tmpq_lkah1l']
[2025-03-04T12:27:32.659-0600] {standard_task_runner.py:105} INFO - Job 25: Subtask SendMessage
[2025-03-04T12:27:32.755-0600] {task_command.py:467} INFO - Running <TaskInstance: EtlWeather.SendMessage scheduled__2025-03-01T00:00:00+00:00 [running]> on host IMNOTROY.
[2025-03-04T12:27:33.092-0600] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='EtlWeather' AIRFLOW_CTX_TASK_ID='SendMessage' AIRFLOW_CTX_EXECUTION_DATE='2025-03-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-01T00:00:00+00:00'
[2025-03-04T12:27:33.094-0600] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-04T12:28:43.579-0600] {job.py:229} INFO - Heartbeat recovered after 50.69 seconds
[2025-03-04T12:29:05.379-0600] {job.py:229} INFO - Heartbeat recovered after 47.23 seconds
[2025-03-04T12:30:19.273-0600] {job.py:229} INFO - Heartbeat recovered after 13.88 seconds
[2025-03-04T12:32:12.085-0600] {job.py:229} INFO - Heartbeat recovered after 118.68 seconds
[2025-03-04T12:32:33.662-0600] {python.py:240} INFO - Done. Returned value was: Done!
[2025-03-04T12:32:33.961-0600] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-04T12:32:33.965-0600] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=EtlWeather, task_id=SendMessage, run_id=scheduled__2025-03-01T00:00:00+00:00, execution_date=20250301T000000, start_date=20250304T182732, end_date=20250304T183233
[2025-03-04T12:32:34.137-0600] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-04T12:32:34.209-0600] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-04T12:32:34.211-0600] {local_task_job_runner.py:245} INFO - ::endgroup::
