[2025-03-02T00:24:59.341-0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-02T00:25:01.514-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: EtlWeather.WeatherAPI manual__2025-03-02T06:23:00.234806+00:00 [queued]>
[2025-03-02T00:25:01.928-0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: EtlWeather.WeatherAPI manual__2025-03-02T06:23:00.234806+00:00 [queued]>
[2025-03-02T00:25:01.960-0600] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-02T00:25:02.963-0600] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): WeatherAPI> on 2025-03-02 06:23:00.234806+00:00
[2025-03-02T00:25:03.057-0600] {standard_task_runner.py:72} INFO - Started process 48631 to run task
[2025-03-02T00:25:03.115-0600] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'EtlWeather', 'WeatherAPI', 'manual__2025-03-02T06:23:00.234806+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/dag_1.py', '--cfg-path', '/tmp/tmpswsxju37']
[2025-03-02T00:25:03.120-0600] {standard_task_runner.py:105} INFO - Job 53: Subtask WeatherAPI
[2025-03-02T00:25:05.827-0600] {task_command.py:467} INFO - Running <TaskInstance: EtlWeather.WeatherAPI manual__2025-03-02T06:23:00.234806+00:00 [running]> on host IMNOTROY.
[2025-03-02T00:25:09.008-0600] {job.py:229} INFO - Heartbeat recovered after 12.83 seconds
[2025-03-02T00:25:22.758-0600] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='EtlWeather' AIRFLOW_CTX_TASK_ID='WeatherAPI' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T06:23:00.234806+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-02T06:23:00.234806+00:00'
[2025-03-02T00:25:23.047-0600] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-02T00:25:27.129-0600] {dag_1.py:28} INFO - Data gotten succesfully!
[2025-03-02T00:25:27.137-0600] {job.py:229} INFO - Heartbeat recovered after 18.28 seconds
[2025-03-02T00:25:27.568-0600] {python.py:240} INFO - Done. Returned value was: {'dt': 1740896726, 'sunrise': 1740920112, 'sunset': 1740962541, 'temp': 291.99, 'feels_like': 291.21, 'pressure': 1015, 'humidity': 49, 'dew_point': 281.06, 'uvi': 0, 'clouds': 0, 'visibility': 10000, 'wind_speed': 3.6, 'wind_deg': 210, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}]}
[2025-03-02T00:25:50.025-0600] {job.py:229} INFO - Heartbeat recovered after 24.94 seconds
[2025-03-02T00:25:50.156-0600] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-02T00:25:50.158-0600] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=EtlWeather, task_id=WeatherAPI, run_id=manual__2025-03-02T06:23:00.234806+00:00, execution_date=20250302T062300, start_date=20250302T062501, end_date=20250302T062550
[2025-03-02T00:25:50.421-0600] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-02T00:25:50.493-0600] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-02T00:25:50.505-0600] {local_task_job_runner.py:245} INFO - ::endgroup::
